### ISSUE TITLE
`org.gnome.Platform` is EOL

### ISSUE THREAD

**Issue by jibsaram** [flathub/com.lakoliu.Furtherance#5]
> Info: runtime org.gnome.Platform branch 43 is end-of-life, with reason:
>   The GNOME 43 runtime is no longer supported as of September 20, 2023. Please ask your application developer to migrate to a supported platform.
> Info: applications using this runtime:
>   com.lakoliu.Furtherance

If at all possible, it'd be great to update this dependency. I hope that won't cause too many challenges.

As always, thank you so much for building this app! It's become my daily tool to keep track of my work :).

**Comment by lakoliu** [comment]
That's awesome to hear! Just updated the runtime to Gnome 44 with the latest release.
